---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "stat /file.txt exists"
    stat:
      path: "/file.txt"
    register: file_txt_stat
  - name: "check if /file.txt exists"
    assert:
      that:
        - file_txt_stat.stat.exists == True
      success_msg: "/file.txt exists"
      fail_msg: "/file.txt doesn't exist"