---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ubuntu2404
    box: jtarpley/ubuntu2404_base
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - 'storage :file, device: "xvdf", size: "5G"'
      - 'storage :file, device: "xvda", size: "4M"'

provisioner:
  name: ansible
  options:
    D: True
    vault_password_file: /etc/ansible/.vault_pass
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../defaults/main.yml
    
verifier:
  name: ansible


