---
# handlers file for bootstrap
- name: update grub configs
  command: update-grub

- name: Reboot host
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: activate cpufreq service
  service: 
    name: cpufrequtils 
    state: restarted 
    enabled: true